/**
 * This class is generated by jOOQ
 */
package com.example.entity.postgres;


import com.example.entity.postgres.tables.Author;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.author
	 */
	public static final Author AUTHOR = Author.AUTHOR;
}
