/**
 * This class is generated by jOOQ
 */
package com.example.entity.postgres.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Author implements Serializable {

	private static final long serialVersionUID = -49925918;

	private Integer id;
	private String  name;

	public Author() {}

	public Author(Author value) {
		this.id = value.id;
		this.name = value.name;
	}

	public Author(
		Integer id,
		String  name
	) {
		this.id = id;
		this.name = name;
	}

	@NotNull
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@NotNull
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Author (");

		sb.append(id);
		sb.append(", ").append(name);

		sb.append(")");
		return sb.toString();
	}
}
